### PR TITLE
Update dependencies and switch to nullsafety

### PR DESCRIPTION
**Pull request by Wikiwix**
Due to the nature of the package the actual library code is already nullsafe and unchanged.
The only necessary changes are 

* the dependency, 
* SDK constraint, 
* unit tests regarding null and
* the travis CI config, so that it uses the current beta instead of dart `2.2`.

### CODE REVIEW

**Comment by Wikiwix** [comment]
@googlebot I fixed it.

**Comment by mit-mit** [comment]
cc @kevmoo

**Review by kevmoo — APPROVED** [review]

**Comment by kevmoo** [comment]
@mit-mit – should I land this?

**Comment by mit-mit** [comment]
Yes, I think that would be great. There are fair number of dependencies of this.

**Comment by kevmoo** [comment]
This is not used by the SDK – but in general we sync to google3 before
publishing

**Comment by Wikiwix** [comment]
@kevmoo  Just realised I missed to update the CHANGELOG.md accordingly.
Will you take care or should I make another PR?

**Comment by kevmoo** [comment]
> @kevmoo Just realised I missed to update the CHANGELOG.md accordingly.
> Will you take care or should I make another PR?

Please do!

**Comment by Wikiwix** [comment]
> > @kevmoo Just realised I missed to update the CHANGELOG.md accordingly.
> > Will you take care or should I make another PR?
> 
> Please do!

See here: https://github.com/google/tuple.dart/pull/25

**Comment by Wikiwix** [comment]
@kevmoo Any word on when this will land as a prerelease?

**Comment by kevmoo** [comment]
I can get this out today!

**Comment by kevmoo** [comment]
Published!

**Comment by Wikiwix** [comment]
Nice! Thanks :)

**Pull request merged**
